[package]
links="slang"
name = "libslang-sys"
version = "0.1.0"
authors = ["Warlock <internalmike@gmail.com>"]
edition = "2018"

[dependencies]
libc = "0.2.72"

[build-dependencies]
cc = { version = "1.0.58", features = ["parallel"] }
pkg-config = "0.3.17"
